### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by mfilippov** [JetBrains/embeddedProjectJdk#7]
java.io.FileNotFoundException: C:\Work\dotnet-teamcity-config\.teamcity\.idea\jdk.table.xml (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:101)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:101)
	at com.jetbrains.embeddedProjectJdk.JdkUtil.readProjectJdkSettings(JdkUtil.kt:55)
	at com.jetbrains.embeddedProjectJdk.JdkUtil.hasDifferentJdkSettings(JdkUtil.kt:38)
	at com.jetbrains.embeddedProjectJdk.EmbeddedProjectJdkSettingsChecker.runActivity(EmbeddedProjectJdkSettingsChecker.kt:24)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:280)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:224)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:419)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:411)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:467)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:443)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:420)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:713)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by mfilippov** [comment]
Fix in 2.1
